services:
  - type: web
    name: sentiment-analysis-backend
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    healthCheckPath: /api/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
